name: Run dstack

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set SSH permissions
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        sudo chown $USER:$USER ~/.ssh

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install and configure dstack
      run: |
        pip install dstack
        dstack config --url https://sky.dstack.ai --project ${{ secrets.DSTACK_PROJECT }} --token ${{ secrets.DSTACK_TOKEN }}
        dstack init
    
    - name: Run dstack dev env
      run: |
        dstack apply -b runpod
